export const MOCK_ORDERS = [
  {
    id: "1",
    orderId: "ORD-1042",
    name: "Sara Al-Mansouri",
    phone: "0501 234 567",
    address: "Al Barsha, Dubai",
    status: "not_called",
    attempts: 0,
    talkTime: null,
    lastCall: null,
    note: null,
  },
  {
    id: "2",
    orderId: "ORD-1039",
    name: "Khalid Ibrahim",
    phone: "0555 887 223",
    address: "Jumeirah, Dubai",
    status: "answered",
    attempts: 1,
    talkTime: "2m 14s",
    lastCall: "10:03",
    note: "Leave at door, apartment 4B. No need to ring bell.",
  },
  {
    id: "3",
    orderId: "ORD-1044",
    name: "Layla Hassan",
    phone: "0509 112 334",
    address: "Marina, Dubai",
    status: "missed",
    attempts: 3,
    talkTime: null,
    lastCall: "10:11",
    note: null,
    duplicatePhone: true,
  },
  {
    id: "4",
    orderId: "ORD-1047",
    name: "Omar Farouk",
    phone: "0522 445 881",
    address: "Downtown, Dubai",
    status: "not_called",
    attempts: 0,
    talkTime: null,
    lastCall: null,
    note: null,
  },
  {
    id: "5",
    orderId: "ORD-1051",
    name: "Fatima Al-Rashid",
    phone: "0503 998 112",
    address: "JLT, Dubai",
    status: "not_called",
    attempts: 0,
    talkTime: null,
    lastCall: null,
    note: null,
  },
  {
    id: "6",
    orderId: "ORD-1053",
    name: "Yusuf Nasser",
    phone: "0551 443 220",
    address: "Silicon Oasis, Dubai",
    status: "not_called",
    attempts: 0,
    talkTime: null,
    lastCall: null,
    note: null,
  },
  {
    id: "7",
    orderId: "ORD-1055",
    name: "Aisha Mahmoud",
    phone: "0507 665 331",
    address: "Business Bay, Dubai",
    status: "not_called",
    attempts: 0,
    talkTime: null,
    lastCall: null,
    note: null,
  },
  {
    id: "8",
    orderId: "ORD-1058",
    name: "Hassan Jaber",
    phone: "0524 778 990",
    address: "Deira, Dubai",
    status: "answered",
    attempts: 1,
    talkTime: "1m 45s",
    lastCall: "09:52",
    note: null,
  },
];